version: "3.9"
services:

   electrumx:
    container_name: electrumx
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 50002:50002
    volumes:
      - /data/electrumx/:/data/
    links:
      - mainnet-garlicoin
    network_mode: host
    restart: always 
