- hosts: all
  become: true

  roles:
    - hostname
    - patching
    - swap
    - docker_install
    - configure_firewall
    - garlic_node
    - electrumx
    - host_monitoring
    - seeder
