version: "3.9"
services:

   seeder:
    container_name: seeder
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 53:53
    links:
      - mainnet-garlicoin
    network_mode: host
    restart: always 
