---

  - name: Setup UFW
    when: firewall_enabled == true
    block: 
      
      - name: UFW Deny Incoming
        ufw:
          direction: incoming
          proto: any
          policy: deny

      - name: UFW Allow Outgoing
        ufw:
          direction: outgoing
          proto: any
          policy: allow

      - name: UFW Allow SSH
        ufw:
          rule: allow
          name: OpenSSH

      - name: Docker Ruleset
        blockinfile:
          path: /etc/ufw/after.rules
          marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
          block: |
            # BEGIN UFW AND DOCKER
            *filter
            :ufw-user-forward - [0:0]
            :DOCKER-USER - [0:0]
            -A DOCKER-USER -j RETURN -s 10.0.0.0/8
            -A DOCKER-USER -j RETURN -s 172.16.0.0/12
            -A DOCKER-USER -j RETURN -s 192.168.0.0/16
            
            -A DOCKER-USER -j ufw-user-forward
            
            -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
            -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
            -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
            -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
            -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
            -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 172.16.0.0/12
            
            -A DOCKER-USER -j RETURN
            COMMIT
            # END UFW AND DOCKER

      - name: Enable UFW
        ufw:
          state: enabled

      - name: Reload UFW
        ufw:
          state: reloaded